travis:
  secure:
    BINSTAR_TOKEN: GrySue7xI3qEG3oGQSbztzT4o+A8OnmnRDZVw6uj5T2xaF+ydZceeNbrLgN1zg3yAUgXSoKVGEqMHVOTpuVp4ARydJqIWb2nU/c5kvGznFMR+cH7zOb6QN7EBwdLxjrKJYCjKZ71L7CP50AxSj9i9xTqaXFFNBaPQSCr3YcThNKAWaSg3MIGId/zstOAEmE0A8JD0L6SIEVYgz82pK9lXvYu0hyNKUPmyqr+TUbyFlnbnu+2XfN88+KOa44jFdWBER0juDVjj9nQlMGnWrh5RNzFNA1JU6NtkLDmgoGV51Y070kT3WUFZuMcoUHIQzvLL7vGuEWg3hY4IzsoHiua6MANLb1E+6kNZH9eIci4THIkfU/4qTESG5Wpk0PXkw/e30ziOutWPG2zFoWF50ZZGdr8y1rzNxY75e50SRdBN2poggzyocwwWZHZzvG1tMFZKcMVxLmJ2798I5eiqlZiOFS89gVUTO8afQmKns3edaJCP4yY1haF60UOliBNQpeGJ2ygz4dmye79NiqqLj7vEhKdFRMO582ihMjAet7awXhrqOW8LY53EvEUw2M8q2TK4y2CdT/395thcCJ4uljKVOOENwSOKRsq+XEvRRuv1j7vTQLDrj/XwXOZ7xGOeahavAOa07SC1wjghQJt3LSFTLaAktrxUrlqThPKXtca6PE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
